spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    hikari:
      connection-test-query: SELECT 1

logging:
  config: classpath:logback.xml
  level:
    com.lixuan.*.*: debug

